---
tap_install:
  version:
    package_version: "1.7.3"
    package_repo_bundle_tag: "1.7.3"
  package_repository:
    oci_repository: "tapgitops.azurecr.io/ys-tap-gitops/tap-packages"
  values:
    profile: view
    ceip_policy_disclosed: true
    
    contour:
      envoy:
        service:
          type: LoadBalancer

    tap_telemetry:
      customer_entitlement_account_number: "123456789"
      installed_for_vmware_internal_use: "true"
