secrets:
    sops:
        age_key: ENC[AES256_GCM,data:klVIRwq0BNnUPh3oynu2kdViTd9hFFpuaP7iwbfxRJK1nVwxC6NWpTnz79VmddqvfRkZDGWaI4Lfpz1Z868tj5E8q6GUSKIJ6fVad2GvJStkIudJ72pv39maWIwvxdGV+A0UWzQk8PemmNSB7CZXmz573ACWbEinnhNh1ZLPJN1LctMe1dyZJL6BbHryrhmvgjifKOCnxQhJlIwuvPWZKcjATi4ScaS716cxjSBg6oVhbMOhYArCiwEesLZz,iv:swxM7FRz1k/wYA8xMVjBIBoZ2XtPXRVql+RkpoX9J+Y=,tag:wtADU9iYZHlPu6BEhuG9dA==,type:str]
        registry:
            hostname: ENC[AES256_GCM,data:U+Q5tO+mNLnKOt5AQN7uxNfaus0=,iv:OuPLIjM+Lqctr3sK6kzQc1H80R8oM6xGY6jWDSTzXWY=,tag:3Cz/xzCZglmn88EKGkruBQ==,type:str]
            username: ENC[AES256_GCM,data:cErRbnT8Gszh,iv:p/yQr0RUcFel7vicleOA6Z57MLmhfSKIuVCryCOFWJk=,tag:SKa8cgaqNx+gEdp4EIwN5A==,type:str]
            password: ENC[AES256_GCM,data:B7qaddRmhITu1bmx20HF04dypGdAioX0t7Xq23vmnHk18Ylwk2tTy0gLdV9ZFqSSRg4yqg==,iv:8i5V83rgXlggpO71y464y6K+dY1mN99Kr2kBgjlMB4g=,tag:4iEIZqNVTNCZcguJm7Rxpg==,type:str]
        git:
            basic_auth:
                username: ENC[AES256_GCM,data:wLYo9Gnv8QBM,iv:qkT9sV9GIZ4idvG5ia9IquuHKeF2oMmWFCmpGyPxOIs=,tag:TKW2tIjdubdtKn8tGfuHGQ==,type:str]
                password: ENC[AES256_GCM,data:7viau59eh2qd3LhqU4Hy1eRtzBDAx3Eem/kDjv9EnM7qDiYlW+aQfbX6JbBM8taMWTwG/vwyTxEUGLAhvicipptgH4A4B0Bm7l9xUvF0FgdsebWBc4rMQObJDiSr,iv:H7NqfVN/V6GkCgaRr55TAu+jP92SPNVN60giOokN8q8=,tag:37aiYREajsVAEHXlwm2QMA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1uz3qsvhwwhu7f794d5lpqkuaw675auq0zph004dc98r3v7n5ac0q82knqx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkV2FYa1VQc1d1WlNZVkRE
            Q3FCNUUrRlRxNmtFenF6Skw0NWZLSzlEOUhVCjNqR09hRUlubndhVVYzeDJOTkxR
            VUNabUJDUTZZSUpZSFZBamo0KzJRa0EKLS0tIHFrSDd4OHVpSUg4MEFJLzNHRW1v
            UFcxN0dlUFVGaE9ENll2bVMrVHVKNmsKL5hmULt2Ta1dHsICpkf0CMa3XsEs8EbX
            SugpVOb3xXRJ4fhlsugO+T/OzYcXbaUKtTYAosaqUeGz1UxRNoRFBA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-02-16T07:21:29Z"
    mac: ENC[AES256_GCM,data:FJNxY3eJ1loRGC1jFCIgJzC1sd6QU6g4xXceZVySpO/Ryn5Dk4/2JYr4PUy3/EIaCXrJXj5Gbga7snnALf5pbErJwczTfJcXWc8Cx5eaHE7n9IxBwX3n6Mjih4/fUZ1FmLi3Q+B12Hnlyaysht7dPj5gT2/dJrLt6PBHd9ZBWtg=,iv:ZsaHyU/tzx4C0/K32sOkp8BuYQwwutN4HD5mbg0QYgQ=,tag:NIzsbcGNym+0PP5JlFcG2A==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
